package internal

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Lease) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "ttl":
			var v int64
			v, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
			z.TTL = time.Duration(v * int64(time.Millisecond))
		case "timestamp":
			err = z.Timestamp.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "expire_at":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "ExpireAt")
					return
				}
				z.ExpireAt = nil
			} else {
				if z.ExpireAt == nil {
					z.ExpireAt = new(Timestamp)
				}
				err = z.ExpireAt.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "ExpireAt")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Lease) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "id"
	err = en.Append(0x84, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "ttl"
	err = en.Append(0xa3, 0x74, 0x74, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(int64(z.TTL / time.Millisecond))
	if err != nil {
		err = msgp.WrapError(err, "TTL")
		return
	}
	// write "timestamp"
	err = en.Append(0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = z.Timestamp.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "expire_at"
	err = en.Append(0xa9, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	if z.ExpireAt == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.ExpireAt.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "ExpireAt")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Lease) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "id"
	o = append(o, 0x84, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "ttl"
	o = append(o, 0xa3, 0x74, 0x74, 0x6c)
	o = msgp.AppendInt64(o, int64(z.TTL/time.Millisecond))
	if err != nil {
		err = msgp.WrapError(err, "TTL")
		return
	}
	// string "timestamp"
	o = append(o, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o, err = z.Timestamp.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// string "expire_at"
	o = append(o, 0xa9, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74)
	if z.ExpireAt == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.ExpireAt.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "ExpireAt")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Lease) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "ttl":
			var v int64
			v, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
			z.TTL = time.Duration(v * int64(time.Millisecond))
		case "timestamp":
			bts, err = z.Timestamp.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "expire_at":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.ExpireAt = nil
			} else {
				if z.ExpireAt == nil {
					z.ExpireAt = new(Timestamp)
				}
				bts, err = z.ExpireAt.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "ExpireAt")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Lease) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 4 + msgp.Int64Size + 10 + z.Timestamp.Msgsize() + 10
	if z.ExpireAt == nil {
		s += msgp.NilSize
	} else {
		s += z.ExpireAt.Msgsize()
	}
	return
}
